data <- read.table("notes.txt")
Y <- as.matrix(data)
ACP <- princomp(Y)
cat("\nValeurs propres\n")
print(ACP$sdev ^ 2)
cat("\nVecteurs propres\n")
print(ACP$loadings)
cat("\n")
print(summary(ACP))

png("ex2ACPPlot.png", width = 400, height = 400)
plot(ACP, type = "lines")
dev.off()
cat("\nex2ACPPlot.png sauvegardee\n")

png("ex2ACPBiplot.png", width = 400, height = 400)
biplot(ACP)
dev.off()
cat("ex2ACPBiplot.png avec C1 et C2 sauvegardee\n")

png("ex2ACPBiplotC1C3.png", width = 400, height = 400)
biplot(ACP, choices = c(1, 3))
dev.off()
cat("ex2ACPBiplotC1C3.png avec C1 et C3 sauvegardee\n")
